##
## Build with appveyor
##
## https://ci.appveyor.com/project/thomasWeise/utils-base
#  
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: if(!(Test-Path -Path 'C:\bin\apache-maven-3.2.5\' )){ cinst maven -Version 3.2.5 }
  # choco does not set the PATH environment variable correctly
  # so we do it manually, like
  # https://github.com/abelsromero/asciidoctor-maven-plugin/blob/master/appveyor.yml
  - cmd: SET PATH=C:\bin\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: mvn --version
  - cmd: java -version
  
cache:
  - C:\bin\apache-maven-3.2.5\

platform:
  - x86
  - x64
  
configuration:
  - Release
    
build_script:
  - mvn clean compile package install -B -Dmaven.test.skip=true
  
test_script:
  - mvn test -B