##
## Build with appveyor
##

install:
  - cinst jdk8
  - cinst maven -version 3.3.1
  - echo %PATH%
  - echo SET PATH=%PATH% > C:\setupPath.bat

platform:
  - x86
  - x64
  
configuration:
  - Release
    
build_script:
  - C:\setupPath.bat
  - mvn clean compile package install
  
test_script:
  - C:\setupPath.bat
  - mvn test