##
## Build with appveyor
##

install:
  - cinst jdk8
  - cinst maven

platform:
  - x86
  - x64
  
configuration:
  - Release
  
before_build:
  - echo %PATH%
  - dir C:\bin\apache-maven-3.3.1\bin
  - mvn.bat clean
  
build_script:
  - mvn.bat compile
  
after_build:
  - mvn.bat package
  
test_script:
  - mvn.bat test
  
after_test:
  - mvn.bat install